#!/bin/sh

client="opAdmin/client/"
server="opAdmin/server/"

rm -rf opAdmin
mkdir opAdmin

mkdir $client
mkdir $server

echo "构建agent服务器中"
cd server
go build 

mv server ../$server
cp config.json ../$server
cp gameTools/* ../$server

echo "构建完毕..."

echo "构建前端网页中..."
cd ../client
rm -rf dist/*
npm run build
cp -r dist ../$client
echo "构建完毕..."

