#!/bin/sh
#
DATABASE=$1
IP=$2
SQLNAME="zonelogdb"

mysql -h $IP -f -u root -pcg2016 -e "create database if not exists ${DATABASE} character set 'utf8';"
mysql -h $IP -f -u root -pcg2016 -B  ${DATABASE} < ${SQLNAME}.sql
mysql -h $IP -f -u root -pcg2016 -e  "show databases" | grep -w $1
